#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Check for interactive terminal
if [ -t 0 ]; then
    echo "ERROR: Interactive terminal detected!"
    echo "Please run without: docker run -it (-i/--interactive, -t/--tty) ..."
    echo "(will attempt shutting down container in 3 seconds)"
    sleep 3
    # Signal s6 to shut down
    s6-svscanctl -t /run/service
    exit 1
fi
