#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if test "$1" -eq 256 ; then
  e=$((128 + $2))
else
  e="$1"
fi

printf "\nApplication exited (%s), shutting down container...\n" "$e"
echo "$e" > /run/s6-linux-init-container-results/exitcode

/run/s6/basedir/bin/halt
