name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: null

jobs:
  test-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, "1.63.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run CLI test
        run: |
          cargo run --release -- -c config.example.toml &
